# docker-compose.yml
version: '3'
services:
  database:
    image: postgres:latest # use latest official postgres version
    env_file:
      - database.env # configure postgres
    command: postgres -c stats_temp_directory=/tmp
    # command: postgres -c stats_temp_directory = '/tmp/stat_temporary'
    volumes:
      - ./.database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - '5432:5432'
volumes:
  database-data: # named volumes can be managed easier using docker-compose